server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Stock?useSSL=false
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
  application:
    name: stockservice

mybatis:
  type-aliases-package: WDM.pojo
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka

seata:
  tx-service-group: eurekaserver-seata-service-group
  service:
    vgroupMapping:
      eurekaserver-seata-service-group: default
    grouplist:
      default: 127.0.0.1:8091
  enabled: true
  data-source-proxy-mode: AT
  registry:
    type: file

