server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Payment?useSSL=false
    username: postgres
    password: Postgresql
    driver-class-name: org.postgresql.Driver
  application:
    name: paymentservice
mybatis:
  type-aliases-package: WDM.pojo
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
